"""Builds the daily fantasy baseball brief text."""
from datetime import date, datetime, timedelta, timezone

from lib.shared import (
    is_hitter,
    is_pitcher,
    batter_sort_score,
    pitcher_sort_score,
    format_batter_line,
    format_pitcher_line,
)


def build_brief(
    team_name: str,
    roster: list[dict],
    scoring_data: dict,
    box_scores: dict[str, dict] | None = None,
    batter_statcast: dict[str, dict] | None = None,
    pitcher_statcast: dict[str, dict] | None = None,
    milb_stats: dict[str, dict] | None = None,
    news_items: list[dict] | None = None,
    transactions: list[dict] | None = None,
    probable_pitchers: list[dict] | None = None,
    target_date: date | None = None,
) -> str:
    """Build the complete daily brief text."""
    if target_date is None:
        target_date = date.today() - timedelta(days=1)
    box_scores = box_scores or {}
    batter_statcast = batter_statcast or {}
    pitcher_statcast = pitcher_statcast or {}
    milb_stats = milb_stats or {}
    news_items = news_items or []
    transactions = transactions or []
    probable_pitchers = probable_pitchers or []

    lines = []
    lines.append("=" * 70)
    lines.append(f"  DAILY FANTASY BRIEF -- {team_name}")
    lines.append(f"  {target_date.strftime('%A, %B %d, %Y')}")
    lines.append("=" * 70)
    lines.append("")

    lines.extend(_build_scoring_summary(scoring_data))
    lines.extend(_build_hitter_section(roster, box_scores, batter_statcast))
    lines.extend(_build_pitcher_section(roster, box_scores, pitcher_statcast))
    lines.extend(_build_milb_section(roster, box_scores, milb_stats))
    lines.extend(_build_news_section(roster, news_items, target_date))
    lines.extend(_build_transactions_section(transactions, roster))
    lines.extend(_build_matchup_preview(probable_pitchers, roster))

    lines.append("")
    lines.append("=" * 70)
    lines.append("  Generated by FantasyBrief")
    lines.append("=" * 70)

    return "\n".join(lines)


def _build_scoring_summary(scoring_data: dict) -> list[str]:
    lines = []
    lines.append("-" * 70)
    lines.append("  TEAM SCORING SUMMARY")
    lines.append("-" * 70)
    if scoring_data:
        matchup_info = scoring_data.get("matchup", {})
        if matchup_info:
            lines.append(f"  Matchup: {matchup_info.get('description', 'N/A')}")
            lines.append(f"  Score:   {matchup_info.get('score', 'N/A')}")
        period_stats = scoring_data.get("period_stats", {})
        if period_stats:
            for stat, value in period_stats.items():
                lines.append(f"  {stat}: {value}")
    lines.append("")
    return lines


# ---------------------------------------------------------------------------
# HITTER SECTION
# ---------------------------------------------------------------------------

def _build_hitter_section(
    roster: list[dict],
    box_scores: dict[str, dict],
    statcast: dict[str, dict],
) -> list[str]:
    lines = []
    lines.append("-" * 70)
    lines.append("  HITTER HIGHLIGHTS")
    lines.append("-" * 70)

    hitters = [p for p in roster if is_hitter(p)]
    if not hitters:
        lines.append("  No hitter data available.")
        lines.append("")
        return lines

    played = [p for p in hitters if p.get("name") in box_scores]
    played.sort(key=lambda p: batter_sort_score(box_scores.get(p.get("name", ""), {})), reverse=True)
    dnp = [p for p in hitters if p.get("name") not in box_scores]

    for player in played:
        name = player.get("name", "Unknown")
        team = player.get("team", "")
        pos = player.get("position", "")
        box = box_scores.get(name, {})
        stats = box.get("stats", {})
        game = box.get("game", "")

        # Traditional stat line: 2-for-4, HR, 2 RBI, R, BB, K
        stat_line = format_batter_line(stats)
        lines.append(f"\n  {name} ({pos}, {team}) -- {game}")
        lines.append(f"    {stat_line}")

        # Statcast underneath
        metrics = statcast.get(name, {})
        if metrics:
            bbe_count = _count_bbe(metrics)
            sc_parts = []
            if bbe_count is not None:
                sc_parts.append(f"{bbe_count} BBE")
            if metrics.get("avg_exit_velo"):
                sc_parts.append(f"Avg EV: {metrics['avg_exit_velo']} mph")
            if metrics.get("max_exit_velo"):
                sc_parts.append(f"Max EV: {metrics['max_exit_velo']}")
            if metrics.get("xBA") is not None:
                sc_parts.append(f"xBA: {metrics['xBA']}")
            if sc_parts:
                lines.append("    Statcast: " + " | ".join(sc_parts))
            sc_parts2 = []
            if metrics.get("hard_hit_pct") is not None:
                sc_parts2.append(f"HardHit%: {metrics['hard_hit_pct']}%")
            if metrics.get("barrels") is not None:
                sc_parts2.append(f"Barrel: {metrics['barrels']}")
            if metrics.get("chase_rate") is not None:
                sc_parts2.append(f"Chase%: {metrics['chase_rate']}%")
            if metrics.get("whiff_rate") is not None:
                sc_parts2.append(f"Whiff%: {metrics['whiff_rate']}%")
            if sc_parts2:
                lines.append("             " + " | ".join(sc_parts2))

    if dnp:
        dnp_names = [p.get("name", "?") for p in dnp]
        lines.append(f"\n  DNP: {', '.join(dnp_names)}")

    lines.append("")
    return lines


def format_batter_line(stats: dict) -> str:
    """Format traditional batter stat line: 2-for-4, HR, 2 RBI, R, BB, K"""
    h = int(stats.get("h", 0))
    ab = int(stats.get("ab", 0))
    parts = [f"{h}-for-{ab}"]
    doubles = int(stats.get("doubles", 0))
    triples = int(stats.get("triples", 0))
    hr = int(stats.get("hr", 0))
    rbi = int(stats.get("rbi", 0))
    r = int(stats.get("r", 0))
    bb = int(stats.get("bb", 0))
    hbp = int(stats.get("hbp", 0))
    k = int(stats.get("k", 0))
    sb = int(stats.get("sb", 0))
    if doubles:
        parts.append(f"{'2B' if doubles == 1 else f'{doubles} 2B'}")
    if triples:
        parts.append(f"{'3B' if triples == 1 else f'{triples} 3B'}")
    if hr:
        parts.append(f"{'HR' if hr == 1 else f'{hr} HR'}")
    if rbi:
        parts.append(f"{'RBI' if rbi == 1 else f'{rbi} RBI'}")
    if r:
        parts.append(f"{'R' if r == 1 else f'{r} R'}")
    if bb:
        parts.append(f"{'BB' if bb == 1 else f'{bb} BB'}")
    if hbp:
        parts.append("HBP")
    if k:
        parts.append(f"{'K' if k == 1 else f'{k} K'}")
    if sb:
        parts.append(f"{'SB' if sb == 1 else f'{sb} SB'}")
    return ", ".join(parts)


def _count_bbe(metrics: dict) -> int | None:
    """Get batted ball event count from Statcast metrics."""
    count = metrics.get("bbe_count")
    return count if count and count > 0 else None


# ---------------------------------------------------------------------------
# PITCHER SECTION
# ---------------------------------------------------------------------------

def _build_pitcher_section(
    roster: list[dict],
    box_scores: dict[str, dict],
    statcast: dict[str, dict],
) -> list[str]:
    lines = []
    lines.append("-" * 70)
    lines.append("  PITCHER HIGHLIGHTS")
    lines.append("-" * 70)

    pitchers = [p for p in roster if is_pitcher(p)]
    if not pitchers:
        lines.append("  No pitcher data available.")
        lines.append("")
        return lines

    played = [p for p in pitchers if p.get("name") in box_scores]
    played.sort(key=lambda p: pitcher_sort_score(box_scores.get(p.get("name", ""), {})), reverse=True)
    dnp = [p for p in pitchers if p.get("name") not in box_scores]

    for player in played:
        name = player.get("name", "Unknown")
        team = player.get("team", "")
        pos = player.get("position", "")
        box = box_scores.get(name, {})
        stats = box.get("stats", {})
        game = box.get("game", "")
        note = stats.get("note", "")

        # Traditional line: 6.0 IP, 4 H, 2 ER, 1 BB, 9 K (92 pitches)
        pitch_line = format_pitcher_line(stats)
        decision = f" {note}" if note else ""
        lines.append(f"\n  {name} ({pos}, {team}){decision} -- {game}")
        lines.append(f"    {pitch_line}")

        # Statcast underneath
        metrics = statcast.get(name, {})
        if metrics:
            sc_parts = []
            if metrics.get("whiff_rate") is not None:
                sc_parts.append(f"Whiff%: {metrics['whiff_rate']}%")
            if metrics.get("csw_pct") is not None:
                sc_parts.append(f"CSW%: {metrics['csw_pct']}%")
            if metrics.get("chase_rate") is not None:
                sc_parts.append(f"Chase%: {metrics['chase_rate']}%")
            if sc_parts:
                lines.append("    Statcast: " + " | ".join(sc_parts))
            sc_parts2 = []
            if metrics.get("avg_exit_velo_against") is not None:
                sc_parts2.append(f"EV Against: {metrics['avg_exit_velo_against']} mph")
            if metrics.get("hard_hit_pct_against") is not None:
                sc_parts2.append(f"HardHit%: {metrics['hard_hit_pct_against']}%")
            if metrics.get("xBA_against") is not None:
                sc_parts2.append(f"xBA Against: {metrics['xBA_against']}")
            if sc_parts2:
                lines.append("             " + " | ".join(sc_parts2))
            pitch_mix = metrics.get("pitch_mix", {})
            if pitch_mix:
                mix_str = ", ".join(f"{pt}: {pct}%" for pt, pct in sorted(pitch_mix.items(), key=lambda x: -x[1]))
                lines.append(f"    Mix: {mix_str}")

    if dnp:
        dnp_names = [p.get("name", "?") for p in dnp]
        lines.append(f"\n  DNP: {', '.join(dnp_names)}")

    lines.append("")
    return lines


def format_pitcher_line(stats: dict) -> str:
    """Format traditional pitcher line: 6.0 IP, 4 H, 2 ER, 1 BB, 9 K (92 pitches)"""
    ip = stats.get("ip", "0")
    h = stats.get("h", "0")
    er = stats.get("er", "0")
    bb = stats.get("bb", "0")
    k = stats.get("k", "0")
    pitches = stats.get("pitches", "0")
    strikes = stats.get("strikes", "0")
    hr = int(stats.get("hr", "0"))
    pitch_info = f"({pitches} pitches, {strikes} strikes)" if int(pitches) > 0 else ""
    hr_part = f", {hr} HR" if hr > 0 else ""
    return f"{ip} IP, {h} H, {er} ER, {bb} BB, {k} K{hr_part} {pitch_info}".strip()


# ---------------------------------------------------------------------------
# MINOR LEAGUE SECTION
# ---------------------------------------------------------------------------

def _build_milb_section(
    roster: list[dict],
    box_scores: dict[str, dict],
    milb_stats: dict[str, dict],
) -> list[str]:
    """Separate section for minor league performances."""
    # Players in MiLB: not in MLB box scores but found in MiLB data
    milb_players = [
        p for p in roster
        if p.get("name") not in box_scores and p.get("name") in milb_stats
    ]
    if not milb_players:
        return []

    lines = []
    lines.append("-" * 70)
    lines.append("  MINOR LEAGUE REPORT")
    lines.append("-" * 70)

    for player in milb_players:
        name = player.get("name", "Unknown")
        team = player.get("team", "")
        pos = player.get("position", "")
        m = milb_stats.get(name, {})
        level = m.get("level", "MiLB")
        game = m.get("game", "")
        stats = m.get("stats", {})
        player_type = m.get("type", "")
        stat_line = stats.get("batting", stats.get("pitching", stats.get("summary", "")))
        lines.append(f"\n  {name} ({pos}, {team}) [{level}] -- {game}")
        if stat_line:
            lines.append(f"    {stat_line}")

    lines.append("")
    return lines


# ---------------------------------------------------------------------------
# NEWS SECTION -- 24h news + injury flags
# ---------------------------------------------------------------------------

def _build_news_section(roster: list[dict], news_items: list[dict], target_date: date) -> list[str]:
    lines = []
    lines.append("-" * 70)
    lines.append("  NEWS & UPDATES")
    lines.append("-" * 70)

    injury_flags = []
    for player in roster:
        for note in player.get("news", []):
            if _is_injury_flag(note):
                injury_flags.append((player.get("name", "?"), note))

    # RotoWire RSS news (primary source -- full summaries)
    rss_covered_players = set()
    if news_items:
        for item in news_items[:15]:
            player = item.get("matched_player", "")
            title = item["title"]
            summary = item.get("summary", "")
            lines.append(f"  [{player}] {title}")
            if summary:
                # Strip the "Visit RotoWire.com..." boilerplate
                clean = summary.split("Visit RotoWire.com")[0].strip()
                if clean:
                    lines.append(f"    {clean}")
            if player:
                rss_covered_players.add(player)

    # Fantrax blurbs as fallback for players not covered by RSS
    fantrax_news = []
    for player in roster:
        name = player.get("name", "?")
        if name in rss_covered_players:
            continue
        for note in player.get("news", []):
            if _is_recent_news(note, target_date):
                fantrax_news.append((name, note, _parse_news_time(note)))

    fantrax_news.sort(key=lambda x: x[2] or "", reverse=True)

    if fantrax_news:
        if news_items:
            lines.append("")
        for name, note, _ts in fantrax_news:
            lines.append(f"  [{name}] {note}")

    if not news_items and not fantrax_news:
        lines.append("  No relevant news for your roster today.")

    # Injury watch -- always shown if there are injuries
    if injury_flags:
        lines.append("")
        lines.append("  INJURY WATCH:")
        for name, note in injury_flags:
            lines.append(f"    {name} -- {note}")

    lines.append("")
    return lines


def _parse_news_time(note: str) -> str | None:
    """Parse a sortable timestamp string from a Fantrax news note.

    Returns 'MM-DD HH:MM' in 24h format for sorting, or None.
    """
    import re
    match = re.match(
        r"^(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s+(\d{1,2}),\s+(\d{1,2}):(\d{2})\s+(AM|PM):",
        note,
    )
    if not match:
        return None
    months = {"Jan": "01", "Feb": "02", "Mar": "03", "Apr": "04", "May": "05", "Jun": "06",
              "Jul": "07", "Aug": "08", "Sep": "09", "Oct": "10", "Nov": "11", "Dec": "12"}
    month = months[match.group(1)]
    day = match.group(2).zfill(2)
    hour = int(match.group(3))
    minute = match.group(4)
    ampm = match.group(5)
    if ampm == "PM" and hour != 12:
        hour += 12
    elif ampm == "AM" and hour == 12:
        hour = 0
    return f"{month}-{day} {hour:02d}:{minute}"


def _is_recent_news(note: str, target_date: date) -> bool:
    """Check if a Fantrax news note falls within the brief's news window.

    For a 10 AM ET run covering yesterday's games, we want news from
    ~10 AM the day before target_date through ~10 AM the day after target_date.
    This captures: pre-game news, game recaps, and overnight/morning updates.
    """
    import re
    _MONTHS = {"Jan": 1, "Feb": 2, "Mar": 3, "Apr": 4, "May": 5, "Jun": 6,
               "Jul": 7, "Aug": 8, "Sep": 9, "Oct": 10, "Nov": 11, "Dec": 12}
    match = re.match(
        r"^(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s+(\d{1,2}),\s+(\d{1,2}):(\d{2})\s+(AM|PM):",
        note,
    )
    if not match:
        # No timestamp — check just date
        date_match = re.match(r"^(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s+(\d{1,2}),", note)
        if not date_match:
            return False
        month = _MONTHS.get(date_match.group(1), 0)
        day = int(date_match.group(2))
        if not month:
            return False
        try:
            note_date = date(target_date.year, month, day)
        except ValueError:
            return False
        diff = (target_date - note_date).days
        return 0 <= diff <= 1

    month = _MONTHS.get(match.group(1), 0)
    day = int(match.group(2))
    hour = int(match.group(3))
    minute = int(match.group(4))
    ampm = match.group(5)
    if ampm == "PM" and hour != 12:
        hour += 12
    elif ampm == "AM" and hour == 12:
        hour = 0
    if not month:
        return False
    try:
        note_dt = datetime(target_date.year, month, day, hour, minute)
    except ValueError:
        return False

    # Window: from 10 AM on (target_date - 1) to 10 AM on (target_date + 1)
    # This gives a full 24h centered on the game day
    window_start = datetime(target_date.year, target_date.month, target_date.day, 10, 0) - timedelta(days=1)
    window_end = datetime(target_date.year, target_date.month, target_date.day, 10, 0) + timedelta(days=1)
    return window_start <= note_dt <= window_end


def _is_injury_flag(note: str) -> bool:
    """Check if a note is an injury status flag (not a dated news item)."""
    # Injury flags don't start with a date, they look like "Knee - Out Indefinitely"
    # or "Injured List - 60-day IL - Elbow"
    import re
    if re.match(r"^(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s+\d", note):
        return False
    injury_keywords = ["injured list", "out indefinitely", "day-to-day", "IL", "injury",
                       "knee", "elbow", "shoulder", "hamstring", "back", "wrist", "oblique"]
    note_lower = note.lower()
    return any(kw in note_lower for kw in injury_keywords)


# ---------------------------------------------------------------------------
# TRANSACTIONS -- rostered players only
# ---------------------------------------------------------------------------

def _build_transactions_section(transactions: list[dict], roster: list[dict]) -> list[str]:
    lines = []
    # Build lookup: (first_initial, last_name) for more precise matching
    roster_keys = set()
    for p in roster:
        name = p.get("name", "")
        if name:
            parts = name.lower().split()
            if len(parts) >= 2:
                roster_keys.add((parts[0][0], parts[-1]))  # (first initial, last name)
                roster_keys.add(name.lower())  # also full name

    relevant = []
    for tx in transactions:
        tx_player = tx.get("player", "").lower()
        tx_parts = tx_player.split()
        if len(tx_parts) < 2:
            continue
        tx_key = (tx_parts[0][0], tx_parts[-1])
        if tx_key in roster_keys or tx_player in roster_keys:
            relevant.append(tx)

    if relevant:
        lines.append("-" * 70)
        lines.append("  TRANSACTIONS")
        lines.append("-" * 70)
        for tx in relevant[:15]:
            lines.append(f"  {tx['player']} ({tx['team']}): {tx['type']}")
            if tx.get("description"):
                lines.append(f"    {tx['description'][:200]}")
        lines.append("")
    return lines


# ---------------------------------------------------------------------------
# MATCHUP PREVIEW
# ---------------------------------------------------------------------------

def _build_matchup_preview(probable_pitchers: list[dict], roster: list[dict]) -> list[str]:
    lines = []
    lines.append("-" * 70)
    lines.append("  TODAY'S MATCHUP PREVIEW")
    lines.append("-" * 70)

    roster_teams = {p.get("team", "").upper() for p in roster if p.get("team")}

    if not probable_pitchers:
        lines.append("  No games scheduled today.")
        lines.append("")
        return lines

    relevant_games = []
    for game in probable_pitchers:
        away = game["away_team"]
        home = game["home_team"]
        for team_abbr in roster_teams:
            if team_abbr and (team_abbr in away.upper() or team_abbr in home.upper()):
                relevant_games.append(game)
                break

    if relevant_games:
        lines.append("  Games with your players:")
        for game in relevant_games:
            lines.append(f"\n  {game['away_team']} @ {game['home_team']}")
            lines.append(f"    Pitchers: {game['away_pitcher']} vs {game['home_pitcher']}")
    else:
        lines.append("  No games today with your rostered players' teams.")
        lines.append("  Full slate:")
        for game in probable_pitchers[:5]:
            lines.append(f"    {game['away_team']} @ {game['home_team']}: {game['away_pitcher']} vs {game['home_pitcher']}")

    lines.append("")
    return lines


